### ISSUE TITLE
[Feature Request] Per World Broadcasts

### ISSUE THREAD

**Issue by realdoomsboygaming** [PandaaaPlays/AutomaticBroadcast#13]
Possible per world broadcasts that are only shown when a player is in a specified world, how this could be done is for example have a "whitelisted-worlds:" option in the config

As an example here is a possible mockup on how it could be configured within the plugin:

```
    exempted-players:
      - exempted-player1
      - exempted-player2
      
     whitelisted-worlds:
      - world
      - world_the_end
      - spawn
```

**Comment by PandaaaPlays** [comment]
Most servers actually need the opposite (blacklisted world(s))... You can achieve the same result with that option :)
